### ISSUE TITLE
Prompts stable diffusion before reply has been fully completed

### ISSUE THREAD

**Issue by XenioxYT** [GuizzyQC/sd_api_pictures_tag_injection#1]
Currently on the latest version of oobabooga webui, had to update Gradio to 3.28.3 to get server.py to open. Think this is whats causing the issue, as an image is generated, however only shows for ~1 frame then disappears, only to be replaced by the text currently being generated by the LLM.

An image is generated, but in about 3 seconds after prompting, and while the LLM is still generating an output which is what leads me to believe that Stable diffusion is being prompted before a text output is sent.

If you need more information (including logs etc) please let me know :)

**Comment by GuizzyQC** [comment]
I think there's a bug with streaming and this extension, the original dev had the extension force streaming off, and the code to do that is still in the extension, but changes in the oobabooga webui might have broken this code. I see Ooba's been working on refactoring the text generation function and has touched some streaming related variables. Can you see if you get the same issue with: a) the original sd_api_pictures extension that's bundled with Oobabooga, and b) streaming off?

Brawlence and Ooba will also probably want to know if the original bundled extension is broken by recent changes.

**Comment by XenioxYT** [comment]
The bundled version of sd_api_pictures works fine, even on the latest version of Gradio. I'll let you know what happens when i disable streaming and will update accordingly. (sd_api_pictures works fine with streaming on in the latest version - I'm pretty sure it temporarily disables streaming until the prompt and image is done, please correct me if I'm wrong!)

**Comment by GuizzyQC** [comment]
Ah, I see the original extension has had changes made to fix it at the same time Ooba's done the refactoring. I'll carry those changes to my extension.

**Comment by GuizzyQC** [comment]
Should be fixed with https://github.com/GuizzyQC/sd_api_pictures_tag_injection/commit/352b47c835c23e6841b0ef6190fccf6abb07e28b

Can you pull and try again?

**Comment by XenioxYT** [comment]
> Should be fixed with [352b47c](https://github.com/GuizzyQC/sd_api_pictures_tag_injection/commit/352b47c835c23e6841b0ef6190fccf6abb07e28b)
> 
> Can you pull and try again?

Yep, I'll put now and try it

**Comment by XenioxYT** [comment]
Beautiful, works perfectly!
